"""
Claude Opus prompts for VibeCode platform.
"""
from .resume_analyzer import RESUME_ANALYZER_SYSTEM, RESUME_ANALYZER_USER
from .vacancy_analyzer import VACANCY_ANALYZER_SYSTEM, VACANCY_ANALYZER_USER
from .resume_vacancy_matcher import MATCHER_SYSTEM, MATCHER_USER
from .task_generator import TASK_GENERATOR_SYSTEM, TASK_GENERATOR_USER
from .hint_generator import HINT_GENERATOR_SYSTEM, HINT_GENERATOR_USER
from .live_assistant import LIVE_ASSISTANT_SYSTEM, LIVE_ASSISTANT_USER
from .solution_reviewer import SOLUTION_REVIEWER_SYSTEM, SOLUTION_REVIEWER_USER
from .ai_detector import AI_DETECTOR_SYSTEM, AI_DETECTOR_USER
from .final_report import FINAL_REPORT_SYSTEM, FINAL_REPORT_USER

__all__ = [
    "RESUME_ANALYZER_SYSTEM", "RESUME_ANALYZER_USER",
    "VACANCY_ANALYZER_SYSTEM", "VACANCY_ANALYZER_USER",
    "MATCHER_SYSTEM", "MATCHER_USER",
    "TASK_GENERATOR_SYSTEM", "TASK_GENERATOR_USER",
    "HINT_GENERATOR_SYSTEM", "HINT_GENERATOR_USER",
    "LIVE_ASSISTANT_SYSTEM", "LIVE_ASSISTANT_USER",
    "SOLUTION_REVIEWER_SYSTEM", "SOLUTION_REVIEWER_USER",
    "AI_DETECTOR_SYSTEM", "AI_DETECTOR_USER",
    "FINAL_REPORT_SYSTEM", "FINAL_REPORT_USER",
]

# пидормот
